language: elixir
elixir:
  - 1.2.3
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get
  - mix dialyzer.plt
script:
  - mix dialyzer --halt-exit-status
  - mix test
after_script:
  - mix deps.get
  - mix inch.report
cache:
  directories:
    - deps
    - plt
