language: elixir
elixir:
    - 1.2.3
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script: mix test    
after_script:
    - mix deps.get
    - mix inch.report
